---
services:
  #pdns-recursor:
  #  image: powerdns/pdns-recursor-master
  #  container_name: pdns-recursor
  #  restart: always
  #  env_file:
  #    - .env_pdns
  #  ports:
  #    - "53:53"
  #    - "53:53/udp"
  #    - "8082:8082"
  #  volumes:
  #    - ./pdns/recursor/recursor.conf.yml:/etc/powerdns/recursor.conf:ro
  #  networks:
  #    powerdns:
  #      ipv4_address: 172.23.0.2
  #  cap_add:
  #    - SYS_TIME

  pdns-auth:
    image: powerdns/pdns-auth-49:4.9.3
    container_name: pdns-auth
    #restart: always
    env_file:
      - .env_pdns
    ports:
      #- "53:53"
      #- "53:53/udp"    
      - "8081:8081"
    volumes:
      - ./pdns/auth/data:/var/lib/powerdns/
      - ./pdns/auth/pdns.conf:/etc/powerdns/pdns.conf
    networks:
      powerdns:
        ipv4_address: 172.23.0.3
    cap_add:
      - SYS_TIME

  pdns-admin:
    image: lamgc/poweradmin:latest
    container_name: pdns-admin
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    #restart: unless-stopped
    env_file:
      - .env_pdns
    volumes:
      #- "./pdns_admin_config/config.inc.php:/var/www/html/inc/config.inc.php"
    networks:
      powerdns:
        ipv4_address: 172.23.0.4
    cap_add:
      - SYS_TIME
    depends_on:
      - pdns-auth

networks:
  powerdns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
