---
services:
  pdns-auth:
    image: powerdns/pdns-auth-49:4.9.3
    container_name: pdns-auth
    ports:
      - "8053:53"
      - "8053:53/udp"
      - "8081:8081"
    volumes:
#      - type: bind
#        source: ./data/powerdns-auth/pdns.sqlite
#        target: /var/lib/powerdns/pdns.sqlite
      - ./pdns/auth/pdns.conf:/etc/powerdns/pdns.conf

  pdns-admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SECRET_KEY='__PDNS_API_KEY__' 
      - SQLA_DB_USER='__PDNS_ADMIN_DB_USER__' 
      - SQLA_DB_PASSWORD='__PDNS_ADMIN_DB_PASSWORD__' 
      - SQLA_DB_HOST='__PDNS_ADMIN_DB_HOST__' 
      - SQLA_DB_NAME='__PDNS_ADMIN_DB_NAME__' 
      - SQLA_DB_PORT='__PDNS_ADMIN_DB_PORT__'
